### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by ghost** [winsbe01/roku-cli#2]
Hello there @winsbe01, I am very sorry to bother you with this. I have been using ur TUI for month with out any issue but today 
I got this:

`Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/niko/.local/bin/roku-tui", line 8, in <module>
    sys.exit(startup())
  File "/home/niko/.local/lib/python3.10/site-packages/roku_tui.py", line 215, in startup
    curses.wrapper(main, config)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/niko/.local/lib/python3.10/site-packages/roku_tui.py", line 172, in main
    remote_loop(stdscr, remote)
  File "/home/niko/.local/lib/python3.10/site-packages/roku_tui.py", line 154, in remote_loop
    press_key(stdscr, remote.keys[c], remote.base_url)
  File "/home/niko/.local/lib/python3.10/site-packages/roku_tui.py", line 63, in press_key
    urllib.request.urlopen(request_url, b'')
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>`

do you mind pointing out how or what to do?

**Comment by winsbe01** [comment]
Hey Juan,

Thanks for reaching out! I'm wondering, did the IP address of your Roku change? This might happen if you don't have a static local IP assigned by your router and the router restarted recently. I've also seen something like this happen if the Roku gets hung up -- a reboot of the Roku usually helps.

One of the things I would like to add is better resiliency to errors like this -- it doesn't need to bounce back, but at least should print something along the lines of "Can't connect to your Roku! Try again?".

Let me know if either of these work for you. I'll see what I can do about some better error handling.

Ben

**Comment by ghost** [comment]
You are totally right... Just needed to upgrade IP address.
Sorry to bother you with such a silly matter.
You know by the way.. pasting long stings when using search method shut it down for me.

Thanks again.

**Comment by winsbe01** [comment]
Hey Juan,

No worries! Glad it worked out. Ideally I'd love the remote to be able to scan the network for Roku devices, but I couldn't get that API working at the time. Maybe I'll try again at some point.

I've not tried copy/pasting strings into the search functionality -- what is your use case? I guess the big one I can think of is credentials when logging into a new application, but I do that very rarely so I don't know what the flow is like. Feel free to open another issue with that error message and I'll take a look.

Ben
