### ISSUE TITLE
Print helpful error message when window size too small

### ISSUE THREAD

**Issue by Nomarian** [winsbe01/roku-cli#3]
As opposed to

```
; roku-tui 
Traceback (most recent call last):
  File "/home/nmz/System/bin/roku-tui", line 8, in <module>
    sys.exit(startup())
  File "/home/nmz/.local/lib/python3.9/site-packages/roku_tui.py", line 215, in startup
    curses.wrapper(main, config)
  File "/usr/local/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/nmz/.local/lib/python3.9/site-packages/roku_tui.py", line 170, in main
    status(stdscr)
  File "/home/nmz/.local/lib/python3.9/site-packages/roku_tui.py", line 87, in status
    stdscr.addstr(20, 1, "~*~ roku-cli ~*~")
_curses.error: addwstr() returned ERR
```

**Comment by winsbe01** [comment]
Fixed with [9707790](https://github.com/winsbe01/roku-tui/commit/97077906455ecd86178611b4dc93f6775226f445)
